evm: update readme.MD
wormholelabs-xyz/example-gmp-router pull request #20
Opened 2024-10-22 18:29 UTC by panoel

2024-10-22 19:33 UTC, evan-gray requested changes
few small things

2024-10-22 19:33 UTC, evan-gray commented on .cspell/custom-dictionary.txt
> +tooManytransceivers
Shouldn't the `t` in Transceivers be capitalized? then it probably wouldn't have had a spellcheck error.

2024-10-22 19:33 UTC, evan-gray commented on evm/README.md
> +An Integrator is the on-chain contract which will call sendMessage on the Router. From the Router’s perspective, the Integrator is the msg.sender of sendMessage. Before an Integrator is able to send
please use backticks for the code references, like `msg.sender` and `sendMessage`?

2024-10-22 19:33 UTC, evan-gray commented on evm/README.md
> +Router-->>AdminContract:revert tooManytransceivers
`tooManyTransceivers` ?

2024-10-22 19:33 UTC, evan-gray commented on evm/README.md
> +### Message Flow:
I feel like this section can be removed for now and potentially replaced with diagrams like the above in the future. The diagrams definitely seem more helpful than the pseudo code.

2024-10-22 20:19 UTC, panoel commented on evm/README.md
> +An Integrator is the on-chain contract which will call sendMessage on the Router. From the Router’s perspective, the Integrator is the msg.sender of sendMessage. Before an Integrator is able to send
Added

2024-10-22 20:20 UTC, panoel commented on evm/README.md
> +Router-->>AdminContract:revert tooManytransceivers
Changed

2024-10-22 20:21 UTC, panoel commented on evm/README.md
> +### Message Flow:
Removed

2024-10-22 20:23 UTC, panoel commented on .cspell/custom-dictionary.txt
> +tooManytransceivers
Removed

2024-10-22 20:24 UTC, panoel commented on .cspell/custom-dictionary.txt
> +tooManytransceivers
Removed

2024-10-23 00:25 UTC, evan-gray approved these changes

2024-10-23 00:25 UTC, merged