evm: add public getters.
wormholelabs-xyz/example-gmp-router pull request #27
Opened 2024-10-25 16:15 UTC by panoel

Add some useful external facing getters.

2024-10-28 13:28 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +    function getTransceiverByIndex(address integrator, uint8 index) external view returns (address result) {
Added

2024-10-28 13:32 UTC, bruce-riley commented on evm/src/Router.sol
> +    /// @return address The address of the administrator contract
"pending administrator contract"?

2024-10-28 13:33 UTC, bruce-riley commented on evm/src/TransceiverRegistry.sol
> +    /// @param integrator The integrator address
Extreme nit: some of the prologue lines end with a period and some don't.

2024-10-28 13:35 UTC, bruce-riley submitted a review, later dismissed

2024-10-28 13:35 UTC, panoel commented on evm/src/Router.sol
> +    /// @return address The address of the administrator contract
Fixed

2024-10-28 13:37 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +    /// @param integrator The integrator address
Maybe just the sentences should have periods and the clauses shouldn't

2024-10-28 13:43 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +    /// @param integrator The integrator address
Fixed

2024-10-29 13:40 UTC, evan-gray requested changes

2024-10-29 13:40 UTC, evan-gray commented on evm/src/TransceiverRegistry.sol
> +        uint256 length = _getRegisteredTransceiversStorage()[integrator].length;
this should simply use `_getTransceiverInfosStorage`, no need for looping

2024-10-29 13:40 UTC, evan-gray commented on evm/src/TransceiverRegistry.sol
> +    /// @dev It is assumed that the integrator address is already validated (and not 0).
what did the periods do to you? :P

2024-10-29 15:02 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +    /// @dev It is assumed that the integrator address is already validated (and not 0).
I blame Bruce.

2024-10-29 15:27 UTC, evan-gray approved these changes

2024-10-29 15:28 UTC, bruce-riley approved these changes

2024-10-29 15:36 UTC, merged