solana: router messages
wormholelabs-xyz/example-gmp-router pull request #28
Opened 2024-10-28 09:11 UTC by bingyuyap

> This PR is ready, I am not.

This PR adds the message related instructions:

**Integrator**
- `send_message` 
- `recv_message`
- `exec_message` 
- `pick_up_message` 

**Tranceiver**
- `attest_message`

and adds these accounts:
- `OutboxMessage` 
- `OutboxMessageKey`
- `AttestationInfo`

and add `UniversalAddress`

> for the specifics of these instructions/accounts/util please refer to <insert readme here>

This PR also does below updates to existing instructions:
- `register` - now inits an `OutboxMessageKey` account per integrator to keep track of the message sequence. This could be done within `IntegratorConfig` but it is cleaner to track configurations and sequence separately

**Mock programs**
- This PR also adds a `mock-transceiver`  program to demonstrate and test the usage of `attest_message` instruction. 
- The mock programs are not cleaned up. These are all CPI calls and are very messy. Will clean up in a separate PR.

2024-10-28 09:17 UTC, bingyuyap commented on svm/programs/mock-integrator/src/lib.rs
> +    use router::instructions::SendMessageArgs;
move this up

2024-10-28 09:18 UTC, bingyuyap commented on svm/programs/mock-integrator/tests/attest_message.rs
> +    // Setup similar to the success test
remove

2024-10-28 09:18 UTC, bingyuyap commented on svm/programs/mock-integrator/tests/common/setup.rs
> +use solana_sdk::signature::{Keypair, Signer};
dont think this is used

2024-10-28 09:20 UTC, bingyuyap commented on svm/programs/mock-integrator/tests/recv_message.rs
> +    // The error should be related to the account not being initialized
it is `AccountNotInitialized`

2024-10-28 09:21 UTC, bingyuyap commented on svm/programs/mock-transceiver/README.md
> +- `InvokeAttest: The struct that defines the accounts required for both invoke_attest_message and invoke_exec_message instructions.
format

2024-10-28 09:22 UTC, bingyuyap commented on svm/programs/router/Cargo.toml
> +solana-sdk = "1.18"
sort by alphabetical order

2024-10-28 09:23 UTC, bingyuyap commented on svm/programs/router/README.md
> +13. `send_message`: Creates a new outbox message for the specified destination chain and address, initializing it with provided information
exec_message and attest_message

2024-10-28 09:25 UTC, bingyuyap commented on svm/programs/router/src/instructions/attest_message.rs
> +    /// The transceiver PDA account, used for signing
To make sure it is the transceiver that is calling this ix

2024-10-28 09:26 UTC, bingyuyap commented on svm/programs/router/src/instructions/attest_message.rs
> +        bump,
i think we need to include bump here?

2024-10-28 09:26 UTC, bingyuyap commented on svm/programs/router/src/instructions/attest_message.rs
> +/// * `args` - The arguments for the instruction, containing message details
document the args here

2024-10-28 09:27 UTC, bingyuyap commented on svm/programs/router/src/instructions/exec_message.rs
> +/// * `args` - The arguments for the exec_message instruction
document args here

2024-10-28 09:28 UTC, bingyuyap commented on svm/programs/router/src/instructions/pick_up_message.rs
> +    msg!("Transceiver Info: {:?}", transceiver_info);
remove this logs

2024-10-28 09:28 UTC, bingyuyap commented on svm/programs/router/src/instructions/pick_up_message.rs
> +    // Check if all transceivers have picked up the message
close if all transceivers have picked up the message

2024-10-28 09:29 UTC, bingyuyap commented on svm/programs/router/src/state/attestation_info.rs
> +    pub fn compute_message_hash(
double check this

2024-10-28 09:31 UTC, bingyuyap commented on svm/programs/universal-address/src/lib.rs
> +    pub fn to_bytes(&self) -> [u8; 32] {
to_be_bytes

2024-10-28 21:26 UTC, evan-gray requested changes
since you are using [return data](https://book.anchor-lang.com/anchor_in_depth/CPIs.html#returning-values-from-handler-functions), it seems worthwhile to provide a method for `getMessageStatus` as well, per the spec.

2024-10-28 21:26 UTC, evan-gray commented on svm/programs/router/src/instructions/attest_message.rs
> +    if attestation_info.message_hash == [0; 32] {
I might have done `src_chain == 0` with a comment that an `IntegratorChainConfig` can't be created for src_chain 0. :shrug: idk how much or not much of a performance difference there

2024-10-28 21:26 UTC, evan-gray commented on svm/programs/router/src/instructions/attest_message.rs
> +            &AttestationInfo::compute_message_hash(
is there a way to avoid computing this hash twice, here and in `::new()`? can save this as an issue for later if you don't immediately have an idea.

2024-10-28 21:26 UTC, evan-gray commented on svm/programs/router/src/instructions/recv_message.rs
> +    pub dst_addr: UniversalAddress,
how about using `integrator_program_id: PubKey` here instead?

2024-10-28 21:26 UTC, evan-gray commented on svm/programs/router/src/instructions/recv_message.rs
> +pub fn recv_message(ctx: Context<RecvMessage>, _args: RecvMessageArgs) -> Result<(u128, u128)> {
should that `Result` use a struct so it's less likely for an integrator to mix up which is the enabled bitmap and which is the attested one?

2024-10-28 21:26 UTC, evan-gray commented on svm/programs/router/src/instructions/exec_message.rs
> +use anchor_lang::prelude::*;
same comments as `recv`

2024-10-28 21:26 UTC, evan-gray commented on svm/programs/router/src/instructions/exec_message.rs
> +    pub integrator_chain_config: Account<'info, IntegratorChainConfig>,
I don't think this account is necessary for this instruction, but maybe it should still be included? might be worth a comment for the motivation.

2024-10-30 03:29 UTC, bingyuyap commented on svm/programs/router/src/instructions/send_message.rs
> +            .is_empty(),
ran a benchmark and it seems like the difference is very negligible 

```
is_empty                time:   [303.95 ps 304.58 ps 305.59 ps]
as_value == 0           time:   [303.97 ps 304.26 ps 304.67 ps]
  ```

2024-10-30 04:54 UTC, bingyuyap commented on svm/programs/router/src/state/attestation_info.rs
> +        let expected_hash: [u8; 32] = [
https://github.com/wormholelabs-xyz/example-gmp-router/issues/31

2024-10-30 04:54 UTC, bingyuyap commented on svm/programs/router/src/state/outbox_message_key.rs
> +pub struct OutboxMessageKey {
changed

2024-10-30 04:54 UTC, bingyuyap commented on svm/programs/router/src/state/attestation_info.rs
> +        Pubkey::find_program_address(&[Self::SEED_PREFIX, &message_hash[..]], &crate::ID)
removed

2024-10-30 04:54 UTC, bingyuyap commented on svm/programs/router/src/state/registered_transceiver.rs
> +#[derive(InitSpace, Debug)]
changed

2024-10-30 04:55 UTC, bingyuyap commented on svm/programs/router/src/instructions/register.rs
> -    /// `init` constraint checks that caller is not already registered
i accidentally pressed dd on the vim

2024-10-30 04:55 UTC, bingyuyap commented on svm/programs/router/src/instructions/send_message.rs
> +        seeds = [b"router_integrator"],
by this did you mean the pda derivations?

2024-10-30 04:55 UTC, bingyuyap commented on svm/programs/router/src/instructions/send_message.rs
> +        src_addr: UniversalAddress::from(ctx.accounts.integrator_program_pda.key()),
updated

2024-10-30 04:56 UTC, bingyuyap commented on svm/programs/router/src/instructions/pick_up_message.rs
> +    pub transceiver_pda_bump: u8,
added

2024-10-30 04:56 UTC, bingyuyap commented on svm/programs/router/src/instructions/pick_up_message.rs
> +    pub refund_recipient: AccountInfo<'info>,
stamped and added a constraint to check if `refund_recipient` is the same as that in `outbox_message`

2024-10-30 04:56 UTC, bingyuyap commented on svm/programs/router/src/state/outbox_message.rs
> +}
added

2024-10-30 04:57 UTC, bingyuyap commented on svm/programs/router/src/instructions/pick_up_message.rs
> +    pub transceiver_info: Account<'info, TransceiverInfo>,
added

2024-10-30 04:57 UTC, bingyuyap commented on svm/programs/router/src/instructions/pick_up_message.rs
> +        .map_err(|_| RouterError::MessageAlreadyPickedUp)?;
my bad, simplified to 

```
 outbox_message
        .outstanding_transceivers
        .set(transceiver_index, false)?; 
```

which propagates the error from `.set()`

2024-10-30 04:58 UTC, bingyuyap commented on svm/programs/router/src/instructions/common/message.rs
> +#[derive(AnchorSerialize, AnchorDeserialize)]
deleted

2024-10-30 04:58 UTC, bingyuyap commented on svm/programs/router/src/instructions/attest_message.rs
> +    if attestation_info.message_hash == [0; 32] {
updated

2024-10-30 04:58 UTC, bingyuyap commented on svm/programs/router/src/instructions/attest_message.rs
> +    pub transceiver_info: Account<'info, TransceiverInfo>,
added

2024-10-30 04:59 UTC, bingyuyap commented on svm/programs/router/src/instructions/attest_message.rs
> +            &AttestationInfo::compute_message_hash(
now we pass in `message_hash` in the args and compare in `AttestationInfo::new()` so we only need to compute it once

2024-10-30 04:59 UTC, bingyuyap commented on svm/programs/router/src/instructions/recv_message.rs
> +    pub dst_addr: UniversalAddress,
changed here and exec_message

2024-10-30 05:00 UTC, bingyuyap commented on svm/programs/router/src/instructions/recv_message.rs
> +pub fn recv_message(ctx: Context<RecvMessage>, _args: RecvMessageArgs) -> Result<(u128, u128)> {
I'm actually iffy about returning results here, as they can just call and check the account data. What do you think?

2024-10-30 05:00 UTC, bingyuyap commented on svm/programs/router/src/instructions/exec_message.rs
> +    pub integrator_chain_config: Account<'info, IntegratorChainConfig>,
deleted

2024-10-30 13:35 UTC, evan-gray commented on svm/programs/router/src/instructions/send_message.rs
> +        seeds = [b"router_integrator"],
I mean that magic string that needs to be used by the integrator “router_integrator” as well as the transceiver one.

2024-10-30 13:36 UTC, evan-gray commented on svm/programs/router/src/instructions/attest_message.rs
> +            &AttestationInfo::compute_message_hash(
I don’t think that solves this, now you just made the integrator compute it and it still gets computed twice, which seems worse.

2024-10-30 13:39 UTC, evan-gray commented on svm/programs/router/src/instructions/recv_message.rs
> +pub fn recv_message(ctx: Context<RecvMessage>, _args: RecvMessageArgs) -> Result<(u128, u128)> {
I think having them load the account is acceptable. Not sure which is cheaper (as loading it themselves requires some checks and parsing). Should be easy to load with just the IDL, I think.

2024-10-30 14:05 UTC, evan-gray commented on svm/programs/router/src/instructions/exec_message.rs
> +    pub src_addr: UniversalAddress,
since this call potentially `init`s the account, it needs to assert that `src_chain != 0`

2024-10-30 14:05 UTC, evan-gray commented on svm/programs/router/src/instructions/exec_message.rs
> +    pub src_chain: u16,
since this call potentially `init`s the account, it needs to assert that `src_chain != 0`

2024-10-30 15:39 UTC, evan-gray commented on .github/workflows/svm.yml
> +      - name: Free Disk Space (Ubuntu)
ew. though as long as this is fast enough, I guess it's one way to keep this working.

2024-10-30 15:39 UTC, evan-gray commented on .github/workflows/svm.yml
> -        working-directory: svm
why was this removed?

2024-10-30 15:39 UTC, evan-gray commented on svm/programs/router/benches/bitmap_benchmark.rs
> +use criterion::{black_box, criterion_group, criterion_main, Criterion};
As I commented, I don't think this local benchmark is meaningful, can probably remove this. It would be more apt to benchmark the compute unit cost on Solana.

2024-10-30 15:39 UTC, evan-gray commented on svm/programs/router/Cargo.toml
> +harness = false
if that benchmark is removed, these can be taken back out

2024-10-30 15:39 UTC, evan-gray commented on svm/programs/router/src/instructions/attest_message.rs
> +        let args = AttestationInfoArgs {
nit: this is only used once, could just make the args in the `new()`

2024-10-30 15:39 UTC, evan-gray commented on svm/programs/router/src/instructions/attest_message.rs
> +    // `IntegratorChainConfig` and `AttestationInfo` can never have chain_id that is 0
technically, right now `AttestationInfo` can have a chain_id that is 0 via `exec_message`. once that is fixed (potentially via a check in `new`), this statement will be true.

2024-10-30 15:39 UTC, evan-gray commented on svm/programs/router/src/instructions/attest_message.rs
> +            &AttestationInfo::compute_message_hash(
to move this along, let's put it back and make an issue for this where we can discuss alternatives.

2024-10-30 15:42 UTC, evan-gray commented on svm/programs/router/src/instructions/pick_up_message.rs
> +        constraint = refund_recipient.key() == outbox_message.refund_recipient
nit: might have used `has_one` on `outbox_message` but :shrug:

2024-10-30 15:43 UTC, bingyuyap commented on svm/programs/router/src/instructions/recv_message.rs
> +pub fn recv_message(ctx: Context<RecvMessage>, _args: RecvMessageArgs) -> Result<(u128, u128)> {
let's have them load the account as of now, removed the return values

2024-10-30 15:48 UTC, evan-gray commented on svm/programs/router/src/instructions/pick_up_message.rs
> +        seeds::program = transceiver_info.transceiver_program_id
nit: might be worth changing this to `args.transceiver_program_id` for consistency.

2024-10-30 15:52 UTC, evan-gray requested changes
mostly nits, should be close. main thing is ensuring `src_chain != 0`

edit: bing was here

2024-10-30 16:55 UTC, bingyuyap commented on svm/programs/router/src/instructions/attest_message.rs
> +        let args = AttestationInfoArgs {
the reason for this args was due to clippy throwing error (more than 8 args). But removing this since we are reverting this back

2024-10-30 17:05 UTC, bingyuyap commented on svm/programs/router/src/instructions/exec_message.rs
> +    pub src_chain: u16,
added src chain and dst chain check in `new`

2024-10-30 17:07 UTC, bingyuyap commented on svm/programs/router/benches/bitmap_benchmark.rs
> +use criterion::{black_box, criterion_group, criterion_main, Criterion};
removed

2024-10-30 17:07 UTC, bingyuyap commented on svm/programs/router/Cargo.toml
> +harness = false
removed

2024-10-30 17:22 UTC, bingyuyap commented on svm/programs/router/src/instructions/pick_up_message.rs
> +        constraint = refund_recipient.key() == outbox_message.refund_recipient
updated

2024-10-30 17:22 UTC, bingyuyap commented on svm/programs/router/src/instructions/pick_up_message.rs
> +        seeds::program = transceiver_info.transceiver_program_id
updated

2024-10-30 17:23 UTC, bingyuyap commented on svm/programs/router/src/instructions/attest_message.rs
> +    // `IntegratorChainConfig` and `AttestationInfo` can never have chain_id that is 0
fixed in `new()`

2024-10-30 17:34 UTC, bingyuyap commented on .github/workflows/svm.yml
> -        working-directory: svm
it gave error previously but now i found a workaround. added it back

2024-10-30 18:37 UTC, evan-gray approved these changes
just some nits at this point, I think

2024-10-30 18:37 UTC, evan-gray commented on svm/programs/router/Cargo.toml
> +criterion = "0.5"
`criterion` is unused?

2024-10-30 18:37 UTC, evan-gray commented on svm/programs/router/src/lib.rs
> +    ///   * `dst_addr`: The destination address as a UniversalAddress.
some of these comments may be out of date now, like `dst_addr`

2024-10-30 18:37 UTC, evan-gray commented on svm/programs/router/src/instructions/recv_message.rs
> +pub fn recv_message(ctx: Context<RecvMessage>, _args: RecvMessageArgs) -> Result<(u128, u128)> {
huh, now I guess they need to load their own integrator_chain_config account and perform the checks 🤔 that's not immediately a problem, but it was kinda nice that they didn't have to think about it. can revisit when more folks with Solana integration experience take a look.

2024-10-30 18:59 UTC, bingyuyap commented on svm/programs/router/src/lib.rs
> +    ///   * `dst_addr`: The destination address as a UniversalAddress.
great catch, should be fixed now

2024-10-30 18:59 UTC, bingyuyap commented on svm/programs/router/Cargo.toml
> +criterion = "0.5"
removed

2024-10-30 21:09 UTC, evan-gray approved these changes

2024-10-30 21:09 UTC, merged