evm: add TransceiverRegistry
wormholelabs-xyz/example-gmp-router pull request #7
Opened 2024-09-20 18:46 UTC by panoel

2024-10-21 17:08 UTC, bruce-riley commented on evm/src/interfaces/IRouterIntegrator.sol
> +    /// @notice Called by a integrator contract to receive a message and mark it executed.
Nit: You cay "Called by a integrator" for most of these, but not `sendMessage`. It's assumed everything in this file is called by the integrator, so you can probably omit that. But if you want to keep it, you should probably add it to `sendMessage`.

Nit Nit: "a integrator" should be "an integrator".

2024-10-21 17:10 UTC, bruce-riley commented on evm/src/interfaces/IRouterAdmin.sol
> +    /// @notice The admin contract calls this function.
Nit: Don't need to say "The admin contract calls this function" because we're in the admin interface file. Should instead say something about what this function does. Same comment on below functions.

2024-10-21 17:49 UTC, panoel commented on evm/src/interfaces/IRouterIntegrator.sol
> +    /// @notice Called by a integrator contract to receive a message and mark it executed.
Removed integrator

2024-10-21 18:20 UTC, panoel commented on evm/src/interfaces/IRouterAdmin.sol
> +    /// @notice The admin contract calls this function.
Fixed.

2024-10-21 18:59 UTC, panoel commented on evm/src/Router.sol
> +            uint256 deliveryPrice = ITransceiver(sendTransceivers[i]).quoteDeliveryPrice(destinationChainId);
Who is supposed to check for NSF?

2024-10-21 19:05 UTC, panoel commented on evm/src/Router.sol
> +        address recipientAddr = UniversalAddressLibrary.toAddress(recipientAddress);
The MessageSequence code uses `address` instead of `UniversalAddress`.  Is that okay?

2024-10-21 19:06 UTC, panoel commented on evm/src/Router.sol
> +        // TODO: We don't have a way to easily get the enabled receive transceivers so we have to loop through all transceivers, which is not good.
I think this is fixed.  Lost track of where the comment belongs.  But all the TODOs are gone.

2024-10-22 14:34 UTC, bruce-riley commented on evm/src/TransceiverRegistry.sol
> +    /// @notice Error when attempting to remove a transceiver
This is used on both enable and disable.

2024-10-22 14:34 UTC, bruce-riley commented on evm/src/TransceiverRegistry.sol
> +    /// @dev Holds send side integrator address => Chain ID => Enabled transceiver address[] mapping.
Nit: This wording of "send side integrator" is confusing. Makes it sound like you are referring to the integrator on the send side, rather than the send side transceiver. Maybe move the "send side" in front of "transceiver". Same comment on "receive side integrator" below.

2024-10-22 14:34 UTC, bruce-riley commented on evm/src/TransceiverRegistry.sol
> +    modifier _onlyRegisteredTransceiver(address integrator, uint16 chain, address transceiver) {
Is it intentional that this modifier starts with an underscore but the one above does not? Also, this one has a prologue and the one above does not.

2024-10-22 14:34 UTC, bruce-riley commented on evm/src/TransceiverRegistry.sol
> +    function _disableRecvTransceiver(address integrator, uint16 chain, address transceiver)
Question: Do these internal functions need to call `_onlyRegisteredTransceiver` again since the caller already did? Is that just wasting gas?

2024-10-22 19:22 UTC, panoel commented on evm/src/Router.sol
> +    function computeMessageHash(
Changed to `_computeMessageDigest`

2024-10-22 19:28 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +    /// @notice Emitted when a transceiver is added.
Added for all the topics.

2024-10-22 19:32 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +    /// @notice Error when attempting to remove a transceiver
Changed.

2024-10-22 19:33 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +    /// @dev Holds send side integrator address => Chain ID => Enabled transceiver address[] mapping.
Changed.

2024-10-22 19:35 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +    modifier _onlyRegisteredTransceiver(address integrator, uint16 chain, address transceiver) {
Changed.

2024-10-22 19:41 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +    function _disableRecvTransceiver(address integrator, uint16 chain, address transceiver)
`onlyRegisteredTransceiver` checks, transceiver address, chain, and transceiver is registered.
The caller uses the `onlyAdmin` modifier to check that the integrator is registered and the caller is authorized.  I don't see a wasteful overlap?

2024-10-22 20:01 UTC, evan-gray commented on evm/src/interfaces/IRouterAdmin.sol
> +    function addTransceiver(address integrator, uint16 chainId, address transceiver) external returns (uint8 index);
this shouldn't need `chainId`

2024-10-22 20:04 UTC, evan-gray commented on evm/src/interfaces/IRouterIntegrator.sol
> +    /// @param initialAdmin The address of the admin. Pass in msg.sender, if you want the integrator to be the admin.
passing in `msg.sender` would make the Integrator's caller the admin. I think passing in `address(this)` would make the Integrator be the admin.

2024-10-22 20:06 UTC, evan-gray commented on evm/src/interfaces/IRouterIntegrator.sol
> +    /// @param refundAddress The source chain refund address passed to the Transceiver.
I'd move `refundAddress` to the end, since it's extra to the spec.

2024-10-22 20:08 UTC, evan-gray commented on evm/src/interfaces/IRouterIntegrator.sol
> +        UniversalAddress dstAddr,
I realized when writing the Aptos code that we probably don't need to pass destination chain and address here (or in `execMessage`), but we can follow up on that separately.

2024-10-22 20:11 UTC, evan-gray commented on evm/src/interfaces/ITransceiver.sol
> +        uint64 sequence,
fwiw, this order is different in the spec (`sequence` is after `srcAddr`).

2024-10-22 20:18 UTC, evan-gray commented on evm/src/Router.sol
> +    /// @param digest The digest of the message.
one of these should be `payloadHash` (from the Integrator) and the other should be `messageHash` (the hash of all the fields). I'm confused about which is which here.

2024-10-22 20:25 UTC, evan-gray commented on evm/src/Router.sol
> +    // =============== Getters ===============================================================
for a follow up PR, should make sure we have getters for all of the storage (pending admin, transceivers, transceiver by index, enabled send, enabled recv)

2024-10-22 20:29 UTC, evan-gray commented on evm/src/Router.sol
> +        address transfer;
we should add this to the spec (the storage wasn't updated with the two-step admin) and unify the name. my vote is for `pending_admin`.

2024-10-22 20:31 UTC, panoel commented on evm/src/interfaces/IRouterAdmin.sol
> +    function addTransceiver(address integrator, uint16 chainId, address transceiver) external returns (uint8 index);
Agreed.

2024-10-22 20:36 UTC, evan-gray commented on evm/src/Router.sol
> +        if (msg.sender == oldAdmin) {
I think these can be simplified by reverting if `msg.sender != oldAdmin && msg.sender != pendingAdmin` and then always setting both and logging. The current emission is also incorrect for a revert. How about

```suggestion
        address oldAdmin = integratorConfigs[integrator].admin;
        address pendingAdmin = integratorConfigs[integrator].transfer;
        address newAdmin = msg.sender;
        if (newAdmin != oldAdmin && newAdmin != pendingAdmin) {
            revert CallerNotAuthorized();
        } 
        // Update the storage with this request.
        integratorConfigs[integrator].admin = newAdmin;
        integratorConfigs[integrator].transfer = address(0);
        emit AdminUpdated(integrator, oldAdmin, newAdmin);
```

2024-10-22 20:39 UTC, evan-gray commented on evm/src/Router.sol
> +    function claimAdmin(address integrator) external {
This doesn't explicitly check that there is an admin transfer pending, not sure if that's okay or not.

2024-10-22 20:52 UTC, evan-gray commented on evm/src/TransceiverRegistry.sol
> +        if (chain == 0) {
this is not part of the spec, but I wonder if it should be?

2024-10-22 20:54 UTC, evan-gray commented on evm/src/TransceiverRegistry.sol
> +        for (uint256 i = 0; i < allTransceiversLength;) {
why does this loop over all of the transceivers, doesn't _getEnabledSendTransceiversArrayForChain have this pre-computed? seems like `getSendTransceiversByChain` should just use that, no?

2024-10-22 20:57 UTC, evan-gray commented on evm/src/Router.sol
> +        uint64 sequence,
similarly, this should be moved above `recipient` to be consistent.

2024-10-22 22:05 UTC, evan-gray commented on evm/src/Router.sol
> +        if (!tsInfo.registered) {
I think this check is repeated by the modifier on `_isRecvTransceiverEnabledForChain`. I'm not sure which is the right place to do it. `_getTransceiverInfosStorage` is also called like 3 times, so maybe there's something more efficient to be done there as well.

2024-10-22 22:16 UTC, evan-gray commented on evm/src/Router.sol
> +        attestationInfo.attestedTransceivers |= uint128(1 << tsInfo.index);
this is missing "MUST check that the Transceiver has NOT already attested."

2024-10-22 22:26 UTC, evan-gray commented on evm/src/Router.sol
> +    ) external payable onlyIntegrator returns (uint128 enabledBitmap, uint128 attestedBitmap) {
is the only integrator check relevant if `_getEnabledRecvTransceiversBitmapForChain` is checked?

2024-10-22 22:29 UTC, evan-gray commented on evm/src/Router.sol
> +    ) external view onlyIntegrator returns (uint128 enabledBitmap, uint128 attestedBitmap, bool executed) {
anyone should be able to call this, not `onlyIntegrator`

2024-10-22 22:30 UTC, evan-gray commented on evm/src/Router.sol
> +        if (!config.isInitialized) {
seems like the only call this check is relevant for is `register`. everywhere else performs some other slot read that would only exist if the integrator had registered, right?

2024-10-22 22:31 UTC, evan-gray commented on evm/src/Router.sol
> +        onlyIntegrator
`onlyIntegrator` may not be needed, it must be registered to have `len != 0` below

2024-10-22 22:32 UTC, evan-gray commented on evm/src/Router.sol
> +    ) external onlyIntegrator {
same as recvMessage

2024-10-22 22:33 UTC, evan-gray commented on evm/src/Router.sol
> +        uint16 sourceChain,
`srcChain` for consistency

2024-10-22 22:33 UTC, evan-gray commented on evm/src/Router.sol
> +        uint16 destinationChain,
`dstChain` for consistency

2024-10-22 22:33 UTC, evan-gray requested changes
only read through router so far but want to get this feedback out.

2024-10-23 11:55 UTC, evan-gray commented on evm/src/TransceiverRegistry.sol
> +/// @dev This contract checks that a few critical invariants hold when transceivers are added or removed,
Transceivers can't be removed and the enabled comment doesn't really make sense here where Transceivers can't be globally enabled/disabled. Maybe rework or just remove this comment? (I assume it was copied from NTT)

2024-10-23 11:59 UTC, evan-gray commented on evm/src/TransceiverRegistry.sol
> +    struct _NumTransceivers {
Is this struct needed anymore? If Transceivers are never removed from the array, you can simply use `_getRegisteredTransceiversStorage()[integrator].length` right?

2024-10-23 12:00 UTC, evan-gray commented on evm/src/TransceiverRegistry.sol
> +    bytes32 private constant NUM_REGISTERED_TRANSCEIVERS_SLOT =
see `_NumTransceivers` comment, then this can be removed.

2024-10-23 12:00 UTC, evan-gray commented on evm/src/TransceiverRegistry.sol
> +    bytes32 private constant REGISTERED_SEND_TRANSCEIVERS_SLOT =
This is not used.

2024-10-23 12:01 UTC, evan-gray commented on evm/src/TransceiverRegistry.sol
> +    function _getNumTransceiversStorage() internal pure returns (mapping(address => _NumTransceivers) storage $) {
see _NumTransceivers comment, then this can be removed.

2024-10-23 12:03 UTC, evan-gray commented on evm/src/TransceiverRegistry.sol
> +    modifier onlyValidTransceiverAndChain(address transceiver, uint16 chain) {
Since this is only used once, can it just be put in the function? I find it much easier to read that way.

2024-10-23 12:07 UTC, evan-gray commented on evm/src/TransceiverRegistry.sol
> +        mapping(address => _NumTransceivers) storage _numTransceivers = _getNumTransceiversStorage();
see _NumTransceivers comment, I think `_getRegisteredTransceiversStorage()[integrator].length` can be used instead

2024-10-23 12:15 UTC, evan-gray commented on evm/src/TransceiverRegistry.sol
> +        return (bitmap & uint128(1 << index)) != 0;
IIRC NTT uses `> 0` because it is cheaper.

2024-10-23 12:18 UTC, evan-gray requested changes
okay, now I think I've reviewed everything but the tests. probably want to revisit public getters, but we can do that in a follow up PR

2024-10-23 12:50 UTC, panoel commented on evm/src/interfaces/ITransceiver.sol
> +        bytes32 refundAddr
Changed.

2024-10-23 12:50 UTC, panoel commented on evm/src/interfaces/ITransceiver.sol
> +        uint64 sequence,
Moved.

2024-10-23 13:27 UTC, panoel commented on evm/src/Router.sol
> +        if (msg.sender == oldAdmin) {
Changed.

2024-10-23 13:32 UTC, bruce-riley commented on evm/src/interfaces/ITransceiver.sol
> +        uint64 sequence,
The update signature matches what I'm expecting.

2024-10-23 13:36 UTC, panoel commented on evm/src/Router.sol
> +    function claimAdmin(address integrator) external {
I fell like that is not okay.  Added a check.

2024-10-23 13:50 UTC, panoel commented on evm/src/Router.sol
> +    ) external view onlyIntegrator returns (uint128 enabledBitmap, uint128 attestedBitmap, bool executed) {
Changed.

2024-10-23 13:52 UTC, panoel commented on evm/src/Router.sol
> +        bool executed = attestationInfo.executed;
Removed.

2024-10-23 14:17 UTC, panoel commented on evm/src/interfaces/IRouterIntegrator.sol
> +    /// @param initialAdmin The address of the admin. Pass in msg.sender, if you want the integrator to be the admin.
Removed comment.

2024-10-23 14:18 UTC, panoel commented on evm/src/interfaces/IRouterIntegrator.sol
> +    /// @param refundAddress The source chain refund address passed to the Transceiver.
Moved.

2024-10-23 14:19 UTC, bruce-riley commented on evm/src/TransceiverRegistry.sol
> +    function _disableRecvTransceiver(address integrator, uint16 chain, address transceiver)
My bad, sorry.

2024-10-23 14:29 UTC, bruce-riley commented on evm/src/interfaces/IRouterAdmin.sol
> +    /// @notice Starts the two step process of transferring admin privileges from the current admin to another contract.
"Completes the two step process".

2024-10-23 14:32 UTC, panoel commented on evm/src/Router.sol
> +        onlyIntegrator
Removed.

2024-10-23 14:33 UTC, panoel commented on evm/src/Router.sol
> +        // sanity check that msg.sender is integrator: The caller has onlyIntegrator.
Removed public to internal redirects.

2024-10-23 14:33 UTC, panoel commented on evm/src/Router.sol
> +    ) external onlyIntegrator {
Removed

2024-10-23 14:34 UTC, panoel commented on evm/src/Router.sol
> +        if (!config.isInitialized) {
Removed

2024-10-23 14:35 UTC, panoel commented on evm/src/Router.sol
> +        uint16 destinationChain,
Changed.

2024-10-23 14:35 UTC, panoel commented on evm/src/Router.sol
> +        uint16 sourceChain,
Changed

2024-10-23 14:40 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +    bytes32 private constant REGISTERED_SEND_TRANSCEIVERS_SLOT =
Removed

2024-10-23 14:40 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +    bytes32 private constant REGISTERED_RECV_TRANSCEIVERS_SLOT =
Removed

2024-10-23 14:42 UTC, panoel commented on evm/src/interfaces/IRouterAdmin.sol
> +    /// @notice Starts the two step process of transferring admin privileges from the current admin to another contract.
Fixed

2024-10-23 15:19 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +        return (bitmap & uint128(1 << index)) != 0;
My testing shows there is no difference.  But I can change anyway.

2024-10-23 15:21 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +/// @dev This contract checks that a few critical invariants hold when transceivers are added or removed,
Removed.

2024-10-23 15:59 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +        mapping(address => _NumTransceivers) storage _numTransceivers = _getNumTransceiversStorage();
Removed.

2024-10-23 16:01 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +    struct _NumTransceivers {
Removed.

2024-10-23 16:05 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +    bytes32 private constant NUM_REGISTERED_TRANSCEIVERS_SLOT =
Removed.

2024-10-23 16:05 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +    function _getNumTransceiversStorage() internal pure returns (mapping(address => _NumTransceivers) storage $) {
Removed.

2024-10-23 16:05 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +    modifier onlyValidTransceiverAndChain(address transceiver, uint16 chain) {
Removed

2024-10-23 16:15 UTC, panoel commented on evm/src/Router.sol
> +    /// @param digest The digest of the message.
Changed.

2024-10-23 18:33 UTC, panoel commented on evm/src/Router.sol
> +        attestationInfo.attestedTransceivers |= uint128(1 << tsInfo.index);
Added.

2024-10-23 20:16 UTC, panoel commented on evm/src/Router.sol
> +        if (!tsInfo.registered) {
Addressed

2024-10-23 20:56 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +        for (uint256 i = 0; i < allTransceiversLength;) {
Fixed

2024-10-24 13:10 UTC, panoel commented on evm/src/Router.sol
> +        address recipientAddr = UniversalAddressLibrary.toAddress(recipientAddress);
Address is fine for MessageSequence

2024-10-24 13:11 UTC, panoel commented on evm/src/TransceiverRegistry.sol
> +///         1. If a transceiver is not registered, it should be enabled.
Not at this time

2024-10-24 13:39 UTC, panoel commented on evm/src/Router.sol
> +    // =============== Getters ===============================================================
Will follow up in a separate PR

2024-10-24 13:39 UTC, panoel commented on evm/src/interfaces/IRouterIntegrator.sol
> +        UniversalAddress dstAddr,
Created an issue for this.

2024-10-24 13:41 UTC, panoel commented on evm/src/Router.sol
> +            uint256 deliveryPrice = ITransceiver(sendTransceivers[i]).quoteDeliveryPrice(destinationChainId);
Testing this out.  TBD.

2024-10-24 14:22 UTC, evan-gray commented on evm/src/TransceiverRegistry.sol
> +        if (chain == 0) {
https://github.com/wormholelabs-xyz/example-gmp-router/issues/24

2024-10-24 19:27 UTC, evan-gray approved these changes

2024-10-24 19:27 UTC, evan-gray commented on evm/src/Router.sol
> +        if (integratorConfigs[integrator].pending_admin == address(0)) {
is it worth doing this check after setting the variable on line 282, then using the variable `pendingAdmin` here? we can do this in a follow up.

2024-10-24 19:27 UTC, evan-gray commented on evm/src/Router.sol
> +        if (!_isRecvTransceiverEnabledForChainWithCheck(integrator, srcChain, msg.sender)) {
something really complex is going on here for something that should be more simple.

1. above, `_getTransceiverInfosStorage` is used to check if the Transceiver is `registered`.
2. the modifier `onlyRegisteredTransceiver` is used on `_isRecvTransceiverEnabledForChainWithCheck` which checks `_getTransceiverInfosStorage()[integrator][transceiver].registered` again
  1. that function `_isRecvTransceiverEnabledForChainWithCheck` only appears to be used here
3. that calls `_isRecvTransceiverEnabledForChain` which loads `_getTransceiverInfosStorage` a third time for `index`

seems to me like `_isRecvTransceiverEnabledForChainWithCheck` could be removed and `_isRecvTransceiverEnabledForChain` could take an index or something. ultimately, this should require 2 storage loads and the following checks

1. `if (!registered) revert`
2. `if ((bitmap & uint128(1 << index)) == 0) revert`

but let's move this to an issue and we can revisit

2024-10-24 19:38 UTC, bruce-riley approved these changes

2024-10-24 20:01 UTC, panoel commented on evm/src/Router.sol
> +        if (!_isRecvTransceiverEnabledForChainWithCheck(integrator, srcChain, msg.sender)) {
This is recorded in issue #25

2024-10-24 20:01 UTC, panoel commented on evm/src/Router.sol
> +        if (integratorConfigs[integrator].pending_admin == address(0)) {
This is recorded in issue #25

2024-10-24 20:06 UTC, merged