solana: router admin
wormholelabs-xyz/example-gmp-router pull request #8
Opened 2024-09-25 14:42 UTC by bingyuyap

This PR adds admin related functionality for the Solana GMP Router:

For more info: check out [svm/programs/router/README.md](https://github.com/wormholelabs-xyz/poc-gmp-router/pull/8/files#diff-ec74889e6f44fc4fb23a81e601f1bd0c2e3c176d7c5bdf1d44a42670a36accdc)

The table shows the instructions, the specs and also the tests that verifies the specs. 

Do not worry, `5,559` lines out of `9,206` lines are from `Cargo.lock` and `2,729` are from tests! 

Events emission is not included in this PR yet!

2024-10-23 14:00 UTC, evan-gray commented on svm/programs/router/src/instructions/add_transceiver.rs
> +    let transceiver_id = ctx.accounts.integrator_config.registered_transceivers.len() as u8;
could call this `index` and simplify line 100

2024-10-23 14:03 UTC, evan-gray commented on svm/programs/router/src/instructions/add_transceiver.rs
> +        has_one = admin @ RouterError::CallerNotAuthorized,
this is redundant with `check_admin`

2024-10-23 14:04 UTC, evan-gray commented on svm/programs/router/src/instructions/disable_transceiver.rs
> +        has_one = admin @ RouterError::CallerNotAuthorized,
this is redundant with `check_admin`

2024-10-23 14:04 UTC, evan-gray commented on svm/programs/router/src/instructions/enable_transceiver.rs
> +        has_one = admin @ RouterError::CallerNotAuthorized,
this is redundant with `check_admin`

2024-10-23 14:04 UTC, evan-gray commented on svm/programs/router/src/instructions/transfer_admin.rs
> +        has_one = admin @ RouterError::CallerNotAuthorized,
this is redundant with `check_admin`

2024-10-23 14:04 UTC, evan-gray commented on svm/programs/router/src/instructions/update_admin.rs
> +        has_one = admin @ RouterError::CallerNotAuthorized,
this is redundant with `check_admin`

2024-10-23 14:10 UTC, evan-gray commented on svm/programs/router/src/state/integrator_chain_config.rs
> +    pub fn new(bump: u8, integrator_program_id: Pubkey, chain_id: u16) -> Self {
feel like I'm missing something, where is this used?

2024-10-23 14:11 UTC, evan-gray commented on svm/programs/router/src/instructions/enable_transceiver.rs
> +        init_if_needed,
how does this set the initial account data? I'm not seeing `new` called anywhere in this file, but maybe I'm missing something.

2024-10-23 14:21 UTC, evan-gray commented on svm/programs/router/src/instructions/update_admin.rs
> +pub struct UpdateAdminArgs {
personally, I might have put all of the admin transfer/claim/update/discard ixs in the same `admin.rs` file and shared this struct, but can do that clean up in a follow up, if desired.

2024-10-23 14:25 UTC, evan-gray commented on svm/programs/router/src/instructions/transfer_admin.rs
> +        constraint = (integrator_config.pending_admin == Some(new_admin.key()) || integrator_config.admin == new_admin.key()) @ RouterError::CallerNotAuthorized,
I don't think that `MUST check that there is an admin transfer pending` is covered.

2024-10-23 14:27 UTC, evan-gray commented on svm/programs/router/src/instructions/transfer_admin.rs
> +    if ctx.accounts.integrator_config.pending_admin.is_some() {
This is a duplicate of `check_admin`

2024-10-23 14:28 UTC, evan-gray commented on svm/programs/router/src/instructions/transfer_admin.rs
> +        constraint = (integrator_config.pending_admin == Some(new_admin.key()) || integrator_config.admin == new_admin.key()) @ RouterError::CallerNotAuthorized,
Also this doesn't check the immutable flag, but maybe we can get rid of that anyway.

2024-10-24 02:51 UTC, bingyuyap commented on svm/programs/router/src/instructions/update_admin.rs
> +pub struct UpdateAdminArgs {
[issue](https://github.com/wormholelabs-xyz/example-gmp-router/issues/22) created

2024-10-24 02:54 UTC, bingyuyap commented on svm/programs/router/src/instructions/transfer_admin.rs
> +        constraint = (integrator_config.pending_admin == Some(new_admin.key()) || integrator_config.admin == new_admin.key()) @ RouterError::CallerNotAuthorized,
added the constraints 
```
        constraint = integrator_config.admin.is_some() @ RouterError::CallerNotAuthorized,
        constraint = integrator_config.pending_admin.is_some() @ RouterError::NoAdminTransferInProgress,
        constraint = integrator_config.pending_admin == Some(new_admin.key()) || integrator_config.admin == Some(new_admin.key()) @ RouterError::CallerNotAuthorized,
```

I don't see EVM having `NoAdminTransferInProgress` so lmk if we want to explicitly throw if there is no pending transfer. It is implicitly checked in `integrator_config.pending_admin == Some(new_admin.key())` but not `integrator_config.admin == Some(new_admin.key())`

2024-10-24 14:06 UTC, evan-gray commented on svm/programs/router/src/instructions/enable_transceiver.rs
> +        init_if_needed,
The other fields of `IntegratorChainConfig` are never populated though. the `bump`, `integrator_program_id`, and `chain_id` are never set. These instructions should have some way of determining if the account is initialized or not and set those fields (or a method on `IntegratorChainConfig` which does both). In this case, you may be able to use `chain_id != 0` if you enforce in `validate` that the `chain_id` arg cannot be `0`

2024-10-24 14:08 UTC, evan-gray requested changes
getting close!

2024-10-24 14:09 UTC, bingyuyap commented on svm/programs/router/src/state/integrator_config.rs
> +            self.admin.is_some() && self.admin == Some(signer.key()),
![image](https://github.com/user-attachments/assets/cb0d72e9-2c57-49cf-be51-3097f59b9e2c)

2024-10-24 15:55 UTC, bingyuyap commented on svm/programs/router/src/instructions/update_admin.rs
> +    ctx.accounts
updated

2024-10-24 15:55 UTC, bingyuyap commented on svm/programs/router/src/state/integrator_config.rs
> +            self.admin.is_some() && self.admin == Some(signer.key()),
updated

2024-10-24 15:56 UTC, bingyuyap commented on svm/programs/router/src/instructions/enable_transceiver.rs
> +        init_if_needed,
updated, added a check where it fails with `InvalidChainId` when `chain_id` = 0 is passed in as arg. We might want to add this to EVM as well

2024-10-24 20:25 UTC, evan-gray commented on svm/programs/router/src/instructions/enable_transceiver.rs
> +        init_if_needed,
I think EVM does have this 

https://github.com/wormholelabs-xyz/example-gmp-router/blob/633b4d9ad7c00560804dce92fb88dda1088545a0/evm/src/TransceiverRegistry.sol#L189-L191

2024-10-24 20:27 UTC, evan-gray approved these changes

2024-10-24 20:34 UTC, merged